import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useMutation, useQuery } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { Sparkles, RefreshCw, AlertCircle } from 'lucide-react'
import { useLanguage } from '../context/LanguageContext'
import { organizationService } from '../services/organizationService'
import api from '../services/api'

const AddJob = () => {
  const navigate = useNavigate()
  const { t } = useLanguage()
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    location: '',
    mode: 'onsite',
    timeCommitment: '',
    requirements: '',
    benefits: '',
    deadline: '',
    category: 'environment'
  })
  const [generating, setGenerating] = useState(false)
  const [aiAvailable, setAiAvailable] = useState(false)

  // Check AI service status
  const { data: aiStatus, isSuccess } = useQuery({
    queryKey: ['aiStatus'],
    queryFn: async () => {
      console.log('🔍 Fetching AI status...')
      const response = await api.get('/ai/status')
      console.log('📦 AI Status Response:', response)
      console.log('📦 Response type:', typeof response)
      console.log('📦 Response keys:', Object.keys(response))
      console.log('📦 response.available:', response.available)
      console.log('📦 response.data:', response.data)
      console.log('📦 response.data?.available:', response.data?.available)
      return response
    },
    refetchOnMount: true,
    refetchOnWindowFocus: false,
    staleTime: 0,
    cacheTime: 0
  })

  // Use useEffect to update aiAvailable when data changes
  useEffect(() => {
    if (isSuccess && aiStatus) {
      console.log('✅ AI Status received:', aiStatus)
      console.log('✅ Data type:', typeof aiStatus)
      console.log('✅ aiStatus.available:', aiStatus?.available)
      
      // Check if available - it's directly on aiStatus.available
      const isAvailable = aiStatus?.available === true
      
      console.log('🤖 Final AI Available:', isAvailable)
      setAiAvailable(isAvailable)
    }
  }, [aiStatus, isSuccess])

  const createMutation = useMutation({
    mutationFn: (data) => organizationService.createOpportunity(data),
    onSuccess: () => {
      toast.success('Opportunity posted successfully!')
      navigate('/org-dashboard')
    },
    onError: (error) => {
      toast.error(error.response?.data?.message || 'Failed to post opportunity')
    }
  })

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData(prev => ({ ...prev, [name]: value }))
  }

  const handleGenerateDescription = async () => {
    // Validation
    if (!formData.title) {
      toast.error('Please enter a title first')
      return
    }
    if (!formData.category) {
      toast.error('Please select a category')
      return
    }
    if (!formData.location) {
      toast.error('Please enter a location')
      return
    }
    if (!formData.requirements) {
      toast.error('Please enter requirements')
      return
    }

    setGenerating(true)
    
    try {
      console.log('🤖 Requesting AI generation...')
      console.log('📤 Request data:', {
        title: formData.title,
        category: formData.category,
        location: formData.location,
        mode: formData.mode,
        requirements: formData.requirements,
        timeCommitment: formData.timeCommitment
      })
      
      const response = await api.post('/ai/generate-description', {
        title: formData.title,
        category: formData.category,
        location: formData.location,
        mode: formData.mode,
        requirements: formData.requirements,
        timeCommitment: formData.timeCommitment
      })

      console.log('✅ AI Generation Response:', response)
      console.log('📄 Description:', response.description)

      const description = response.description
      
      if (description) {
        setFormData(prev => ({
          ...prev,
          description: description
        }))
        toast.success('✨ Description generated by AI!', { duration: 4000 })
      } else {
        console.error('❌ No description in response')
        toast.error('Failed to generate description')
      }
    } catch (error) {
      console.error('❌ AI generation error:', error)
      const errorMsg = error.response?.data?.message || error.message || 'Failed to generate description'
      toast.error(errorMsg)
    } finally {
      setGenerating(false)
    }
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    createMutation.mutate(formData)
  }

  // Debug: Log AI status changes
  useEffect(() => {
    console.log('🔄 AI Available state changed:', aiAvailable)
  }, [aiAvailable])

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-xl shadow-lg p-8">
        <div className="mb-6">
          <h2 className="text-3xl font-bold text-gray-900 mb-2">{t('addJob')}</h2>
          <p className="text-gray-600">Create a new volunteer opportunity</p>
        </div>

        {/* AI Status Banner */}
        {aiAvailable ? (
          <div className="mb-6 bg-gradient-to-r from-purple-50 to-pink-50 border-2 border-purple-200 rounded-xl p-4">
            <div className="flex items-start gap-3">
              <Sparkles className="w-6 h-6 text-purple-600 flex-shrink-0 mt-0.5" />
              <div>
                <h3 className="font-bold text-gray-900 mb-1">🤖 AI Description Generator Available!</h3>
                <p className="text-sm text-gray-700">
                  Fill in the basic details below, and our AI will generate a professional, 
                  engaging description for you using advanced Machine Learning.
                </p>
              </div>
            </div>
          </div>
        ) : (
          <div className="mb-6 bg-yellow-50 border-2 border-yellow-200 rounded-xl p-4">
            <div className="flex items-start gap-3">
              <AlertCircle className="w-5 h-5 text-yellow-600 flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-sm text-yellow-800">
                  AI service is currently unavailable. Make sure Ollama is running: 
                  <code className="ml-1 bg-yellow-100 px-2 py-1 rounded">ollama serve</code>
                </p>
              </div>
            </div>
          </div>
        )}
        
        <form className="space-y-6" onSubmit={handleSubmit}>
          {/* Title */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              {t('jobTitle')} <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              name="title"
              value={formData.title}
              onChange={handleChange}
              placeholder="e.g., Beach Cleanup Volunteer"
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent"
              required
            />
          </div>

          {/* Category */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              {t('category')} <span className="text-red-500">*</span>
            </label>
            <select
              name="category"
              value={formData.category}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent"
              required
            >
              <option value="environment">{t('environment')}</option>
              <option value="education">{t('education_cat')}</option>
              <option value="healthcare">{t('healthcare')}</option>
              <option value="community">{t('community')}</option>
              <option value="animals">{t('animals')}</option>
              <option value="arts">{t('arts')}</option>
            </select>
          </div>

          {/* Location */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              {t('location')} <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              name="location"
              value={formData.location}
              onChange={handleChange}
              placeholder="e.g., Yangon, Myanmar"
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent"
              required
            />
          </div>

          {/* Mode */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              {t('mode')} <span className="text-red-500">*</span>
            </label>
            <select
              name="mode"
              value={formData.mode}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent"
              required
            >
              <option value="onsite">{t('onsite')}</option>
              <option value="remote">{t('remote')}</option>
              <option value="hybrid">{t('hybrid')}</option>
            </select>
          </div>

          {/* Time Commitment */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              {t('timeCommitment')} <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              name="timeCommitment"
              value={formData.timeCommitment}
              onChange={handleChange}
              placeholder="e.g., 5 hours/week, Weekends only, Flexible"
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent"
              required
            />
          </div>

          {/* Requirements */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              {t('requirements')} <span className="text-red-500">*</span>
            </label>
            <textarea
              name="requirements"
              value={formData.requirements}
              onChange={handleChange}
              placeholder="e.g., Good physical fitness, Enthusiastic attitude, Team player"
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent"
              rows="3"
              required
            ></textarea>
          </div>

          {/* Description with AI Generator */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="block text-sm font-medium text-gray-700">
                {t('description')} <span className="text-red-500">*</span>
              </label>
              {aiAvailable && (
                <button
                  type="button"
                  onClick={handleGenerateDescription}
                  disabled={generating || !formData.title || !formData.requirements}
                  className="flex items-center gap-2 bg-gradient-to-r from-purple-600 to-pink-600 text-white px-4 py-2 rounded-lg hover:from-purple-700 hover:to-pink-700 font-medium disabled:opacity-50 disabled:cursor-not-allowed transition-all text-sm"
                >
                  {generating ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4" />
                      Generate with AI
                    </>
                  )}
                </button>
              )}
            </div>
            <textarea
              name="description"
              value={formData.description}
              onChange={handleChange}
              placeholder={aiAvailable ? "Click 'Generate with AI' to auto-generate a professional description, or write your own..." : "Write a compelling description..."}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent"
              rows="6"
              required
            ></textarea>
            {aiAvailable && (
              <p className="text-xs text-gray-500 mt-1">
                💡 Tip: Fill in Title, Category, Location, and Requirements first, then click "Generate with AI"
              </p>
            )}
          </div>

          {/* Benefits */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              {t('benefits')} (Optional)
            </label>
            <textarea
              name="benefits"
              value={formData.benefits}
              onChange={handleChange}
              placeholder="e.g., Certificate, Free meals, Transportation"
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent"
              rows="3"
            ></textarea>
          </div>

          {/* Deadline */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              {t('deadline')} <span className="text-red-500">*</span>
            </label>
            <input
              type="date"
              name="deadline"
              value={formData.deadline}
              onChange={handleChange}
              min={new Date().toISOString().split('T')[0]}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-transparent"
              required
            />
          </div>

          {/* Submit Button */}
          <button
            type="submit"
            disabled={createMutation.isPending}
            className="w-full bg-emerald-600 text-white py-3 rounded-lg hover:bg-emerald-700 font-medium disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {createMutation.isPending ? 'Posting...' : t('post')}
          </button>
        </form>
      </div>
    </div>
  )
}

export default AddJob
